spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fake_provider
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/fake_provider
    user: postgres
    password: postgres

base:
  url: https://65e858db4bb72f0a9c4f041d.mockapi.io/webhook
  
server:
  port: 8083